apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-12-07T17:17:19Z"
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.23.0
    control-plane: controller
  name: notification-controller
  namespace: flux-system
  resourceVersion: "2871"
  uid: b7ca56e8-918a-4154-baad-5e47cad039cf
spec:
  clusterIP: 10.96.220.54
  clusterIPs:
  - 10.96.220.54
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: notification-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
