apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-12-07T17:17:19Z"
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.23.0
    control-plane: controller
  name: source-controller
  namespace: flux-system
  resourceVersion: "2876"
  uid: 74f6ddad-fdef-4585-90b6-c1390d79b11e
spec:
  clusterIP: 10.96.168.210
  clusterIPs:
  - 10.96.168.210
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: source-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
